open Types;;
let template = [

    (* question (don't edit these)                                                "short answer", "long answer notes" *)
H("integer arithmetic");
  Q("usual arithmetic conversions",                                                 "          ", "");
  Q("arithmetic UBs",                                                               "          ", "");
  Q("ABI variants",                                                                 "          ", "");
H("floats");
  Q("floating types",                                                               "          ", "");
H("characters and strings");
  Q("string literals (incl. potential aliasing)",                                   "          ", "");
  Q("C11 character-set features",                                                   "          ", "");
H("structured data");
  Q("basic structs",                                                                "          ", "");
  Q("basic enums",                                                                  "          ", "");
  Q("basic unions",                                                                 "          ", "");
  Q("struct-as-value memory accesses and arguments/returns",                        "          ", "");
  Q("union-as-value memory accesses and arguments/returns",                         "          ", "");
  Q("compound type initialisers",                                                   "          ", "");
  Q("bitfields",                                                                    "          ", "");
  Q("flexible array members",                                                       "          ", "");
  Q("variable length arrays",                                                       "          ", "");
H("control flow");
  Q("C loose ISO specification of evaluation order",                                "          ", "");
  Q("loops (for, while, do, break, continue)",                                      "          ", "");
  Q("switch (structured)",                                                          "          ", "");
  Q("switch (general)",                                                             "          ", "");
  Q("C goto within a block",                                                        "          ", "");
  Q("C goto leaving a block",                                                       "          ", "");
  Q("C goto entering a block",                                                      "          ", "");
  Q("function pointers",                                                            "          ", "");
  Q("non-local jumps (setjump.h)",                                                  "          ", "");
  Q("signal handling (signal.h)",                                                   "          ", "");
H("function calls");
  Q("mutable function parameters",                                                  "          ", "");
  Q("variadic arguments",                                                           "          ", "");
  Q("function parameters of array type with \"static\" or *",                       "          ", "");
H("lifetime");
  Q("block lifetimes (precise or lifted to function scope)",                        "          ", "");
  Q("thread-local storage",                                                         "          ", "");
H("memory object model");
  Q("basic model (fully concrete/fully abstract/CompCert block+offset/PNVI-ae-udi/whatever)", "", "");
  Q("passing addresses of locals in function calls",                                "          ", "");
  Q("storing addresses of locals (e.g. in globals)",                                "          ", "");
  Q("pointer/integer casts (incl. arith on unused/unused bits)",                    "          ", "");
  Q("pointer arithmetic using offset-of",                                           "          ", "");
  Q("subobject provenance",                                                         "          ", "");
  Q("effective types",                                                              "          ", "");
  Q("uninitialised reads",                                                          "          ", "");
  Q("restrict",                                                                     "          ", "");
  Q("register",                                                                     "          ", "");
H("concurrency");
  Q("unsequenced races",                                                            "          ", "");
  Q("idealised SC concurrency",                                                     "          ", "");
  Q("C/C++11",                                                                      "          ", "");
  Q("Linux-kernel",                                                                 "          ", "");
  Q("volatile",                                                                     "          ", "");
H("other");
  Q("C11 generic selection",                                                        "          ", "");
  Q("multiple compilation units",                                                   "          ", "");
  Q("standard library",                                                             "          ", "");
  Q("common (GCC/Clang) non-ISO extensions",                                        "          ", "");
  ]
